### PR TITLE
Fixing searchbar

### PR DESCRIPTION
**Pull request by JanSchneider1**

### CODE REVIEW

**Comment by czarnecki** [comment]
Code looks fine. Unfortunately I can't test it on my machine right now. So if somebody else can assure that it works fine we can merge this.

**Comment by ccaylak** [comment]
I'll Test it

**Comment by ccaylak** [comment]
Current status is not working, please don't merge yet

**Comment by JanSchneider1** [comment]
@ccaylak I agree, merging the master in this branch would solve this

**Comment by ccaylak** [comment]
It's working now. Unfortunately I don't have test data to search through

**Pull request merged**
